# Generated by Django 6.0.6 on 2026-06-25 09:44

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Smartphones', 'Smartphones'), ('Chargers', 'Chargers'), ('Back Covers', 'Back Covers')], db_index=True, max_length=20)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['id'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='catalog_pro_tags_7c2650_gin')],
            },
        ),
    ]
